version: "3.7"
services:

  gallery:
    container_name: gallery
    build: .
    image: tchalko/gallery:v2
    ports:
      - "80"

  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nikkyron

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080"

networks:
  default:
    external:
      name: nikkyrron-net

volumes:
  db-data: