version: '3'

services:
  jenkins-app:
    container_name: jenkins
    image: jenkins/jenkins:lts-alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /mnt/jenkins:/var/jenkins_home

networks:
  default:
    external:
      name: nikkyrron-net